trigger:
- main  # this pipeline will trigger on push to main branch

variables:
  nodeVersion: '18.x'  # set Node.js version

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'  # set VM image
    steps:
    - checkout: self  # checkout code from repository
    - task: UseNode@1  # use Node.js in pipeline
      inputs:
        version: $(nodeVersion)

    # Install dependencies
    - script: npm install
      displayName: 'npm install'

    # Run lint
    - script: npm run lint
      displayName: 'Run lint'

    # Run tests
    - script: npm test
      displayName: 'Run tests'

    # Build application
    - script: npm run build
      displayName: 'Build application'